package com.code.secretary.enums.workflow;

public enum WFTaskRolesEnum {
	REQUESTER,
	NOTIFICATION,
	VIEWER,

	DIRECT_MANAGER,
	SECONDARY_DIRECT_MANAGER,

	MANAGER_REDIRECT,
	REVIEWER_EMP_REDIRECT,
	SECONDARY_MANAGER_REDIRECT,

	SECONDARY_REVIEWER_EMP,
	REVIEWER_EMP,

	SECONDARY_SIGN_MANAGER,
	SIGN_MANAGER;
}
