package com.code.secretary.enums;

public enum ConfigurationEnum {
	SETUP_PATH,
	SECURITY_PATH,

	UNIFIED_UPLOADER_DELETE_PATH,
	UNIFIED_UPLOADER_DOWNLOAD_PATH,
	UNIFIED_UPLOADER_UPLOAD_PATH,

	AUDIT_ENABLED,
	AUDIT_JSON_OBJ_ENABLED,

	REPORTS_ROOT,

	ADMIN_USER,

	JMS_SERVER_URL,

	SECRETARY_PATH, // will be used by the scheduler only

	DEFAULT_LATITUDE,
	DEFAULT_LONGITUDE,
	DEFAULT_TIMEZONE,
	PRAYER_REMINDER_IN_MINUTES,
	PRAYER_REMIND_AGAIN_IN_MINUTES,
	STOP_PRAYER_REMIND_AGAIN_IN_MINUTES,

	MEETING_APPOINTMENT_REMINDER_IN_MINUTES;

}
